"""empty message

Revision ID: 4ee282c0a38d
Revises: 0980be3893d1
Create Date: 2024-07-25 11:00:47.487598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee282c0a38d'
down_revision = '0980be3893d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.JSON(), nullable=False))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('bar_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bar_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.DOUBLE(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.DOUBLE(), nullable=False))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
