"""add coordinates theme hours

Revision ID: 7127257700a9
Revises: 4ee282c0a38d
Create Date: 2024-07-30 14:05:41.380077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7127257700a9'
down_revision = '4ee282c0a38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('theme', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hours', sa.String(), nullable=True))
        batch_op.drop_column('location')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_column('review')

    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sqlite.JSON(), nullable=False))
        batch_op.drop_column('hours')
        batch_op.drop_column('theme')
        batch_op.drop_column('coordinates')

    # ### end Alembic commands ###
