"""add location

Revision ID: 977723eb944e
Revises: 7127257700a9
Create Date: 2024-07-30 14:10:14.217672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977723eb944e'
down_revision = '7127257700a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
